# Theme Settings
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin : "mint"

# Site Settings
locale                 : "en-US"
title                  : "Brady Nakamura"
title_separator        : "|"
subtitle               : "Design x Engineering x Additive Manufacturing"
name                   : "Brady Kiyoshi Nakamura"
description            : "Portfolio of work in mechanical design, additive manufacturing, and aesthetic engineering."
url                    : "https://yourusername.github.io" # Replace with your actual domain
baseurl                : ""
repository             : "bradynakamura/bradynakamura.github.io" # Replace if using a different repo name
logo                   : "/assets/images/logo.png" # Replace if applicable
masthead_title         : " "
breadcrumbs            : false
words_per_minute       : 200
enable_copy_code_button: true
copyright              : "Brady Nakamura"
search                 : true
search_provider        : lunr
lunr:
  search_within_pages  : true

# Social Sharing
og_image               : "/assets/images/og-image.jpg" # Replace with your banner image
social:
  type: Person
  name: "Brady Nakamura"
  links:
    - "https://github.com/bradynakamura"
    - "https://www.linkedin.com/in/bradynakamura/"
    - "https://www.instagram.com/bradynakamura/" # optional
    - "mailto:brady@example.com"

# Site Author
author:
  name             : "Brady Nakamura"
  avatar           : "/assets/images/avatar.jpg" # Replace with your image
  bio              : "Mechanical engineer with a passion for additive manufacturing, computational design, and quiet aesthetics."
  location         : "San Luis Obispo, CA"
  email            : "brady@example.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:brady@example.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bradynakamura"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bradynakamura"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bradynakamura"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bradynakamura"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/bradynakamura"

# Timezone
timezone: "America/Los_Angeles"

# Markdown, Sass, and Plugins remain unchanged from default
